In [1]:
#Create a numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Creation of 0D array 

import numpy as np

arr = np.array(42)

print(arr)

42


In [4]:
#Creation of 1D array 

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [6]:
# Creation of 2D array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
# Creation of 3D array

import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
#Using ndimenssion to find dimenssion of array

import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
3


In [16]:
#Acess array elements

import numpy as np 

arr = np.array([1,2,3,4])

print(arr[1])

2


In [17]:
import numpy as np 

arr = np.array([1,2,3,4])

print(arr[0])

1


In [18]:
#Adding according to the index of array

import numpy as np 

arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


In [22]:
#Acess 2D arrays

import numpy as np 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd element on the 1st row:',arr[0,1])

2nd element on the 1st row: 2


In [23]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[1:5])

[2 3 4 5]


In [25]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:5])  #Here start of index is not given which is considered as 0 to 4 index

[1 2 3 4 5]


In [26]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])  #Here end of index is not given which is considered as 4 to 6

[5 6 7]


In [28]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:])  #Here start and end both of index is not given which is considered as 0 to 7 index

[1 2 3 4 5 6 7]


In [1]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])  #Here start of index is not given which is considered as 0 to 3 index

[1 2 3 4]


In [2]:
#Negative Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])  #Here -1 one element is not considered and also here index starts from behind and 0 index is not considered from right hand side 

[5 6]


In [3]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2])  #Here 2 means alternate slicing btw the start to end index means if i take it as 1:6:2 result would be 2,4,6

[2 4]


In [1]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[::2]) # Here we are slicing each element alternatively from start to end of the array 

[1 3 5 7]


In [2]:
#Slicing in 2D Arrays

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


In [5]:
import numpy as np

arr = np.array([[1,2,3,],[4,5,6],[7,8,9]])

element = arr[1,2]     #SELLECT THE ELEMENT AT ROW INDEX 1 , COLUMN INDEX 2 (VALUE 6)

print(element)

6


In [7]:
#ROW SLICING 

import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

row_slice = arr[0:2,:]    #Select the rows with the index 0 and 1 , all columns #Output [[1,2,3],[4,5,6]]

print(row_slice)

[[1 2 3]
 [4 5 6]]


In [8]:
#COLUMN SLICING 

import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

col_slice = arr[:,1:3]    #Selct all the rows , columns with index 1 and 2 # Output [[2,3],[5,6],[8,9]]

print(col_slice)

[[2 3]
 [5 6]
 [8 9]]
